version: '3.8'
services:
  db:
    image: postgres:15
    container_name: organize-simple-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: organize-simple
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  app:
    build:
      context: .
      target: production
    container_name: organize-simple-app
    restart: always
    environment:
      NODE_ENV: production
      LOG_LEVEL: 'debug, verbose'
      DATABASE_URL: postgresql://postgres:root@organize-simple-db:5432/organize-simple?schema=public
      POPPLER_BIN_PATH: /usr/bin
      OPENAI_API_KEY: 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
    ports:
      - '3000:3000'
    depends_on:
      - db
volumes:
  db_data:
    name: organize-simple-data
networks:
  organize_simple_network:
    name: organize_simple_network
