name: CI

on:
  push:
    branches:
      - main
    paths:
      - '**.js'
      - '**.jsx'
      - '**.ts'
      - '**.tsx'
      - '**.yml'
      - '**.json'

concurrency:
  group: ${{github.head_ref}}
  cancel-in-progress: true

jobs:
  install-cache:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18]
    steps:
      - name: Checkout commit
        uses: actions/checkout@v2
      - name: Use Node.js ${{matrix.node}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node}}
      - name: Cache npm dependencies
        uses: actions/cache@v2
        id: cache-dependenies
        with:
          path: node_modules
          key: ${{runner.os}}-npm-${{hashFiles('**/package-lock.json')}}
          restore-keys: |
            ${{runner.os}}-npm-
      - name: Install Dependencies
        if: steps.cache-dependenies.outputs.cache-hit != 'true'
        run: |
          npm install
